name: deploy to pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npm run deploy

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
# steps:
#   - uses: actions/checkout@v2
#   - uses: actions/setup-node@v1
#     with:
#       node-version: 12
#       registry-url: https://registry.npmjs.org/
# - name: setup git authentication
#   run: |
#     git config --global user.email "<me>@<gmail>.com"
#     git config --global user.name "<my_name>"
#     git remote set-url origin https://<user>:<token>@github.com/<user>/<repo>
# - name: publish package
#   run: |
#     yarn
#     npm run deploy
