name: deploy to pages

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v1
    with:
      node-version: 12
      registry-url: https://registry.npmjs.org/
  # - name: setup git authentication
  #   run: |
  #     git config --global user.email "<me>@<gmail>.com"
  #     git config --global user.name "<my_name>"
  #     git remote set-url origin https://<user>:<token>@github.com/<user>/<repo>
  - name: publish package
    run: |
      yarn
      npm run deploy
